version: 2
jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "'run' statements can actually contain a 'name' and 'command' argument as well"
          command: echo "You can even have multiline commands."
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: mkdir ~/cache/
      - run: echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths:
            - /cache
  test:
    docker:
      - image: circleci/node
    parallelism: 2
    steps:
      - run:
          command: |
            TESTFILES=$(circleci tests glob "__test__/**/*.spec.{sh}" | circleci tests split --split-by=timings)
            npm test $TESTFILES
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh
      - run:
          name: Run Goodbye test
          command: |
            bash src/test_goodbye.sh

workflows:
  version: 2
  test:
    jobs:
      - build
      - test